spring:
  application:
    name: account
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    username: root
    password: kiss4400
    url: jdbc:mysql://59.110.234.213:3306/zhangpei?useUnicode=true&characterEncoding=UTF-8
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5 #  数据库连接池的最小维持连接数
      initial-size: 5  #  初始化提供的连接数
      max-total: 20 #  最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间

## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: org.nix.zhangpei.account.model # 注意：对应实体类的路径
  config-location:  classpath:mybatis/mybatis.cfg.xml


server:
  tomcat:
    uri-encoding: UTF-8