security:
  oauth2:
    client:
      # 指定客户端信息
      client-id: love-blog
      client-secret: love-blog
      # 当用户需要认证时跳转到认证服务器上
      user-authorization-uri: http://127.0.0.1:8080/sso/server/oauth/authorize
      # 去认证服务器拿取口令
      access-token-uri: http://127.0.0.1:8080/sso/server/oauth/token
    resource:
      jwt:
        # 去服务器的密钥
        key-uri: http://127.0.0.1:8080/sso/server/oauth/token_key
server:
  port: 8082
  context-path: /blog