spring:
  application:
    name: evaluation
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:org.nix.lovedomain.dao.mapper/*Mapper.xml
  configuration:
    cache-enabled: false
logging:
    level:
      com.threefivework.mymall.dao.mapper: DEBUG