spring:
  datasource:
      url: jdbc:mysql://wds001:3306/evaluation_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: bisha520
  http:
   encoding:
     charset: UTF-8
     force: true
     enabled: true
  session:
    store-type: redis
  redis:
#      host: 59.110.234.213
      host: 127.0.0.1
      # 链接超时
      timeout: 2000
      jedis:
        pool:
          min-idle: 5
          max-active: 10
          max-idle: 10
          max-wait: 2000
security:
  basic:
    enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
love:
  security:
    browser:
      loginPage: /login/index.html