spring:
  application:
    name: love-recording
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    username: root
    password: kiss4400
    url: jdbc:mysql://59.110.234.213:3306/zhangpei?useUnicode=true&characterEncoding=UTF-8
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5 #  数据库连接池的最小维持连接数
      initial-size: 5  #  初始化提供的连接数
      max-total: 20 #  最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: org.nix.zhangpei.love.recording.dao.po
  config-location:  classpath:mybatis/mybatis.cfg.xml
mapper:
  style: normal
#log
logging:
  file: resources/love-recording/src/log/logger.log
  level: debug