-- ---------
-- USER 用户表，权限由用户组决定，默认两个组，管理组和用户组，后续再定
-- ---------
CREATE TABLE USER (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
 GROUP_ID BIGINT(8) DEFAULT 1 COMMENT '用户组ID,默认为使用用户的最少权限',
 USER_NAME VARCHAR(32) NOT NULL COMMENT '用户名',
 USER_PWD VARCHAR(64) NOT NULL COMMENT '用户密码',
 USER_PHONE BIGINT(12) COMMENT '用户手机号码',
 USER_SEX VARCHAR(6) DEFAULT '未知' COMMENT '用户性别',
 USER_QQ BIGINT(9) COMMENT '用户QQ号码',
 USER_EMAIL VARCHAR(64) DEFAULT '' COMMENT '用户EMAIL地址',
 USER_ADDRESS VARCHAR(255) DEFAULT '' COMMENT '用户地址',
 USER_MARK BIGINT(9) DEFAULT 0 COMMENT '用户积分',
 USER_RANK_ID INT(3) DEFAULT 1 COMMENT '用户等级',
 USER_LAST_LOGIN_IP VARCHAR(15) COMMENT '用户上一次登录IP地址',

 USER_BIRTHDAY BIGINT(13) COMMENT '用户生日',
 USER_DESCRIPTION VARCHAR(255) COMMENT '自我描述',
 USER_IMAGE_URL VARCHAR(255) DEFAULT 'HTTPS://DWZ.CN/WNE7H0NR' COMMENT '用户头像存储路径,使用短地址存储，调用百度短地址',
 USER_SCHOOL VARCHAR(255)  COMMENT '毕业学校',
 USER_REGISTER_TIME BIGINT(13) NOT NULL COMMENT '用户注册时间',
 USER_REGISTER_IP VARCHAR(15) NOT NULL COMMENT '用户注册时IP地址',
 USER_LAST_UPDATE_TIME BIGINT(13) COMMENT '用户上次更新博客时间',
 USER_WEIBO VARCHAR(255) COMMENT '用户微博',
 USER_BLOOD_TYPE CHAR(10) DEFAULT '未知' COMMENT '用户血型',
 USER_SAYS VARCHAR(255) COMMENT '用户语录',
 USER_ACTIVATION INT(3) DEFAULT 1 COMMENT '是否激活，0为激活，1为未激活',
 USER_FREEZE INT(3) DEFAULT 0 COMMENT '是否冻结，0为不冻结，1为冻结',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;
ALTER TABLE `USER`
ADD UNIQUE INDEX `USER_NAME_UNQ` (`USER_NAME`) COMMENT '用户名唯一索引',
ADD UNIQUE INDEX `USER_PHONE_UNQ` (`USER_PHONE`)  COMMENT '用户手机号唯一索引',
ADD UNIQUE INDEX `USER_QQ_UNQ` (`USER_QQ`)  COMMENT '用户QQ唯一索引',
ADD UNIQUE INDEX `USER_EMAIL_UNQ` (`USER_EMAIL`)  COMMENT '用户邮箱唯一索引';

-- ---------------
-- USER_RANK 用户等级表
-- ---------------
CREATE TABLE USER_RANK (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 USER_RANK BIGINT(5) NOT NULL COMMENT '等级',
 RANK_MARK BIGINT(6) NOT NULL COMMENT '等级积分',
 RANK_NAME VARCHAR(32) NOT NULL COMMENT '等级名称',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;
INSERT INTO USER_RANK(ID,USER_RANK,RANK_MARK,RANK_NAME) VALUES (1,1,0,'普通会员');

-- --------------
-- USER_GROUP 用户组表，用户组拥有多个资源，一个资源属于多个用户组
-- --------------
CREATE TABLE USER_GROUP (
 ID BIGINT(3) NOT NULL AUTO_INCREMENT COMMENT '自增ID号',
 GROUP_DESCRIPTION VARCHAR(50) NOT NULL COMMENT '用户组描述',
 GROUP_NAME VARCHAR(20) NOT NULL COMMENT '用户组名',
 GROUP_PRENT BIGINT(3) COMMENT '用户组的上一级，该级包含了上级的所有权限，如果为最低级则为空',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;
INSERT INTO USER_GROUP(ID, GROUP_DESCRIPTION, GROUP_NAME) VALUES (1,"使用用户所属的基础组","USER");
INSERT INTO USER_GROUP(ID, GROUP_DESCRIPTION, GROUP_NAME) VALUES (2,"管理组，管理人员的分组","ADMIN");

-- --------------
-- GROUP_RESOURCE 用户组表-资源关联表
-- --------------
CREATE TABLE GROUP_RESOURCE(
 ID BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 GROUP_ID BIGINT(8) NOT NULL COMMENT '用户组ID',
 RESOURCE_ID BIGINT(10) NOT NULL COMMENT '系统资源ID',
 PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 ;

-- ----------------
-- POWER_LIST 用户资源表，一个资源属于多个用户组，一个用户组拥有多个资源
-- ----------------
CREATE TABLE SYS_RESOURCE (
 ID BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 RESOURCE_NAME VARCHAR(36) NOT NULL COMMENT '资源名字',
 RESOURCE_URL VARCHAR(255) NOT NULL COMMENT '资源URL',
 RESOURCE_SWITCH INT(1) DEFAULT 0 COMMENT '资源开关,0为开，1为关',
 RESOURCE_DESCRIPTION VARCHAR(36) NOT NULL COMMENT '权限描述',
 RESOURCE_TYPE INT(5) NOT NULL COMMENT '资源类型',
 RESOURCE_PRENT BIGINT(10) COMMENT '父级资源',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;
INSERT INTO SYS_RESOURCE(RESOURCE_NAME,RESOURCE_URL,RESOURCE_DESCRIPTION,RESOURCE_TYPE)
VALUES('测试资源','https://dwz.cn/K9EQw03R','csdn博客地址',1);


-- -----------------
-- FRIEND 好友表
-- -----------------
CREATE TABLE FRIEND (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 USER_ID BIGINT(8) NOT NULL COMMENT '用户ID',
 FRIEND_ID BIGINT(8) NOT NULL COMMENT '好友ID',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;


-- --------------------
-- USER_ATTENTION 用户关注表
-- --------------------
CREATE TABLE USER_ATTENTION (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 USER_ID BIGINT(8) NOT NULL COMMENT '用户ID',
 ATTENTION_ID BIGINT(8) NOT NULL COMMENT '关注用户的ID',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;


-- ---------------------
-- SECRET_MESSAGE 用户私信表
-- ---------------------
CREATE TABLE SECRET_MESSAGE (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '自增私信ID',
 SEND_ID BIGINT(8) NOT NULL COMMENT '发信者ID',
 RECEIVE_ID BIGINT(8) NOT NULL COMMENT '收信者ID',
 MESSAGE_TOPIC VARCHAR(64) NOT NULL COMMENT '私信标题',
 MESSAGE_CONTENT VARCHAR(255) NOT NULL COMMENT '私信内容',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- ----------------------
-- SYSTEM_MESSAGE 系统通知表
-- ----------------------
CREATE TABLE SYSTEM_MESSAGE (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '系统通知ID',
 SEND_ID BIGINT(8) NOT NULL COMMENT '接受者ID',
 GROUP_ID INT(3) NOT NULL COMMENT '用户组ID',
 SEND_DEFAULT BIGINT(8) NOT NULL COMMENT '1时发送所有用户，0时则不采用',
 SYSTEM_TOPIC VARCHAR(60) NOT NULL COMMENT '通知内容',
 SYSTEM_CONTENT VARCHAR(255) NOT NULL COMMENT '通知内容',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;


-- ------------------------
-- FRIENDLY_LINK 友情链接
-- ------------------------
CREATE TABLE FRIENDLY_LINK (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '友情链接自增ID',
 LINK_NAME VARCHAR(60) NOT NULL COMMENT '友情链接名称',
 LINK_URL VARCHAR(255) NOT NULL COMMENT '链接地址',
 LINK_LOGO VARCHAR(255) NOT NULL COMMENT 'LOGO图片',
 SHOW_ORDER INT(3) NOT NULL COMMENT '在页面显示的顺序',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;


-- ------------------------
-- AD 广告表
-- ------------------------
CREATE TABLE AD (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 POSITION_ID BIGINT(5) NOT NULL COMMENT '0,站外广告;从1开始代表的是该广告所处的广告位,同表AD_POSTITION中的字段POSITION_ID的值',
 MEDIA_TYPE INT(3) NOT NULL DEFAULT 0 COMMENT '广告类型,0图片;1FLASH;2代码3文字',
 AD_NAME VARCHAR(60) NOT NULL COMMENT '该条广告记录的广告名称',
 AD_LINK VARCHAR(255) NOT NULL COMMENT '广告链接地址',
 AD_CODE TEXT NOT NULL COMMENT '广告链接的表现,文字广告就是文字或图片和FLASH就是它们的地址',
 START_TIME BIGINT(13) NOT NULL DEFAULT 0 COMMENT '广告开始时间',
 END_TIME BIGINT(13) NOT NULL DEFAULT 0 COMMENT '广告结束时间',
 LINK_MAN VARCHAR(60) NOT NULL COMMENT '广告联系人',
 LINK_EMAIL VARCHAR(60) NOT NULL COMMENT '广告联系人的邮箱',
 LINK_PHONE VARCHAR(60) NOT NULL COMMENT '广告联系人得电话',
 CLICK_COUNT BIGINT(8) NOT NULL DEFAULT 0 COMMENT '广告点击次数',
 ENABLED INT(3) NOT NULL DEFAULT 1 COMMENT '该广告是否关闭;1开启; 0关闭; 关闭后广告将不再有效',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;


-- ------------------
-- STAY_MESSAGE 用户留言表
-- ------------------
CREATE TABLE STAY_MESSAGE (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '留言表自增ID',
 USER_ID BIGINT(8) NOT NULL COMMENT '用户ID',
 STAY_USER_ID BIGINT(8) NOT NULL COMMENT '留言者ID',
 MESSAGE_CONTENT VARCHAR(255) NOT NULL COMMENT '留言内容',
 STAY_USER_IP VARCHAR(15) NOT NULL COMMENT '留言用户的IP地址',
 MESSAGE_STAY_TIME BIGINT(13) NOT NULL COMMENT '留言时间',
 PLACE VARCHAR(64) NOT NULL COMMENT '地区',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;


-- --------------------
-- ABOUT_BLOG 博客信息表
-- --------------------
CREATE TABLE ABOUT_BLOG (
 ID BIGINT(8) NOT NULL  COMMENT '用户ID',
 BLOG_KEYWORD VARCHAR(255) NOT NULL COMMENT '博客关键字',
 BLOG_DESCRIPTION VARCHAR(255) NOT NULL COMMENT '博客描述',
 BLOG_NAME VARCHAR(36) NOT NULL COMMENT '博客名称',
 BLOG_TITLE VARCHAR(128) NOT NULL COMMENT '博客标题',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- ----------------------
-- VISITOR 最近访客表
-- ----------------------
CREATE TABLE VISITOR (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '访客记录ID',
 VISITOR_ID BIGINT(8) NOT NULL COMMENT '访客ID',
 VISITOR_TIME BIGINT(13) NOT NULL COMMENT '来访时间',
 USER_ID BIGINT(8) NOT NULL COMMENT '被访用户ID',
 VISITOR_IP VARCHAR(15) NOT NULL COMMENT '访客IP地址',
 TYPE_ID INT(3) NOT NULL COMMENT '访问板块ID',
 WHERE_ID BIGINT(8) NOT NULL COMMENT '查看某板块的某个子项目，如查看相册板块的第3个相册，该ID对应该相册的ID号',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- -----------------------
-- SHUOSHUO 用户心情说说表
-- -----------------------
CREATE TABLE SHUOSHUO (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '说说记录ID',
 USER_ID BIGINT(8) NOT NULL COMMENT '用户ID',
 SHUO_TIME BIGINT(13) NOT NULL DEFAULT 0 COMMENT '发布时间',
 SHUO_IP VARCHAR(15) NOT NULL COMMENT '说说发布时的IP地址',
 SHUOSHUO VARCHAR(255) NOT NULL COMMENT '说说内容',
 TYPE_ID INT(3) NOT NULL DEFAULT 3 COMMENT '栏目ID,默认为3',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- -----------------------
-- PHOTO_SORT 相片分类表
-- -----------------------
CREATE TABLE PHOTO_SORT (
 ID BIGINT(8) NOT NULL  AUTO_INCREMENT COMMENT '相册ID',
 SORT_IMG_NAME VARCHAR(20) NOT NULL COMMENT '相册名',
 SORT_IMG_TYPE VARCHAR(20) NOT NULL COMMENT '展示方式 0->仅主人可见,1->输入密码即可查看,2->仅好友能查看,3->回答问题即可查看',
 IMG_PASSWORD VARCHAR(32) NOT NULL COMMENT '查看密码',
 USER_ID BIGINT(8) NOT NULL COMMENT '所属用户ID',
 IMG_SORT_QUESTION VARCHAR(255) NOT NULL COMMENT '访问问题',
 IMG_SORT_ANSWER VARCHAR(128) NOT NULL COMMENT '访问问题的答案',
 TYPE_ID INT(3) NOT NULL DEFAULT 1 COMMENT '默认1表示相册板块',
 TOP_PIC_SRC BIGINT(8) NOT NULL COMMENT '封面图片的路径',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- -----------------------
-- PHOTOS 相片表
-- -----------------------
CREATE TABLE PHOTOS (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '相片ID',
 PHOTO_NAME VARCHAR(255) NOT NULL COMMENT '相片名称',
 PHOTO_SRC VARCHAR(255) NOT NULL COMMENT '图片路径',
 PHOTO_DESCRIPTION VARCHAR(255) NOT NULL COMMENT '图片描述',
 USER_ID BIGINT(8) NOT NULL COMMENT '所属用户ID',
 SORT_ID BIGINT(8) NOT NULL COMMENT '所属相册ID',
 UPLOAD_TIME BIGINT(13) NOT NULL COMMENT '图片上传时间',
 UPLOAD_IP VARCHAR(15) NOT NULL COMMENT '图片操作上传IP地址',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;




-- -------------------------
-- ARTICLE_SORT 文章分类表
-- -------------------------
CREATE TABLE ARTICLE_SORT (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '文章自增ID',
 USER_ID BIGINT(8) NOT NULL COMMENT '该分类所属用户',
 SORT_ARTICLE_NAME VARCHAR(60) NOT NULL COMMENT '分类名称',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- --------------------------
-- ARTICLE 文章表
-- --------------------------
CREATE TABLE ARTICLE (
 ID BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '日志自增ID号',
 ARTICLE_NAME VARCHAR(128) NOT NULL COMMENT '文章名称',
 ARTICLE_TIME BIGINT(13) NOT NULL COMMENT '发布时间',
 ARTICLE_IP VARCHAR(15) NOT NULL COMMENT '发布IP',
 ARTICLE_CLICK INT(10) NOT NULL COMMENT '查看人数',
 SORT_ARTICLE_ID BIGINT(8) NOT NULL COMMENT '所属分类',
 USER_ID BIGINT(8) NOT NULL COMMENT '所属用户ID',
 TYPE_ID INT(3) NOT NULL DEFAULT 1 COMMENT '栏目ID',
 ARTICLE_TYPE INT(13) NOT NULL DEFAULT 1 COMMENT '文章的模式:0为私有，1为公开，2为仅好友查看',
 ARTICLE_CONTENT TEXT NOT NULL COMMENT '文章内容',
 ARTICLE_UP INT(3) NOT NULL DEFAULT 0 COMMENT '是否置顶:0为否，1为是',
 ARTICLE_SUPPORT INT(3) NOT NULL DEFAULT 0 COMMENT '是否博主推荐:0为否，1为是',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;




-- --------------------------
-- USER_COMMENT 用户评论表
-- --------------------------
CREATE TABLE USER_COMMENT (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '评论自增ID号',
 USER_ID BIGINT(8) NOT NULL COMMENT '收到评论的用户ID',
 TYPE_ID INT(3) NOT NULL COMMENT '评论栏目ID',
 COMMIT_ID BIGINT(8) NOT NULL COMMENT '评论内容的ID',
 COMMIT_CONTENT VARCHAR(255) NOT NULL COMMENT '评论内容',
 COMMIT_USER_ID BIGINT(8) NOT NULL COMMENT '评论者ID',
 COMMIT_TIME BIGINT(13) NOT NULL COMMENT '评论时间',
 COMMIT_IP VARCHAR(15) NOT NULL COMMENT '评论时的IP地址',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;



-- ----------------------------
-- PHONE_MESSAGE 短信记录表
-- ----------------------------
CREATE TABLE PHONE_MESSAGE (
 ID BIGINT(8) NOT NULL AUTO_INCREMENT COMMENT '自增ID号',
 PHONE_NUM VARCHAR(12) NOT NULL COMMENT '用户手机号码',
 CONTENTS VARCHAR(255) NOT NULL COMMENT '发送内容',
 SEND_TIME BIGINT(13) NOT NULL COMMENT '发送时间',
 USER_ID BIGINT(8) NOT NULL COMMENT '用户ID',
 PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ;