spring:
  datasource:
    username: root
    password: kiss4400
    url: jdbc:mysql://59.110.234.213:3306/love?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*  #不统计这些请求数据
      stat-view-servlet:
        #访问监控网页的登录用户名和密码
        login-username: root
        login-password: love

