server:
  port: 9030
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: love-oauth2-service
  datasource:
    username: root
    password: kiss4400
    url: jdbc:mysql://59.110.234.213:3306/love?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
#    root: debug
    com.example.demo.dao: debug
  file: doc/log/testLog.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath*:org/nix/zpbs/mapper/*.xml

love:
  security:
    browser:
      # 自定义登陆页面
      loginPage: /login/signIn.html
      # 登陆操作请求路径
      loginRequestUrl: /authentication/form
      # 配置登陆后的处理方式，分为跳转和JSON返回,默认为JSON返回
#      loginType: REDIRECT
    validate:
      image:
        url: /test/hello/* #验证是否可以通过配置拦截到用户请求
        expireIn: 180
        imageConfigFileName: image.properties
      sms:
        url: /test/hello/* #验证是否可以通过配置拦截到用户请求
        expireIn: 180
    social:
      qq:
#        在腾讯申请的应用
        appId: XXXX
        appSecret: XXX
#       请求回调地址
        providerId: weixin
      filterProcessesUrl: /love

