server:
  port: 9030
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: love-oauth2-service
  datasource:
    username: root
    password: kiss4400
    url: jdbc:mysql://59.110.234.213:3306/love?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    root: debug
    com.example.demo.dao: debug
  file: doc/log/testLog.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath*:org/nix/zpbs/mapper/*.xml

love:
  security:
    browser:
      # 自定义登陆页面
      loginPage: /login/signIn.html
      # 配置登陆后的处理方式，分为跳转和JSON返回,默认为JSON返回
#      loginType: REDIRECT
