server:
  port: 9020
spring:
  application:
    name: love-blog-application
  profiles:
    active: dev
logging:
  level:
    root: info
    com.example.demo.dao: debug
  file: doc/log/testLog.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath*:org/nix/zpbs/mapper/*.xml