server:
  port: 9020
spring:
  application:
    name: love-blog-application
  profiles:
    active: dev
logging:
  level:
    root: info
  path: C:\WorkPace\GIT\love\doc\log
  file: log.log
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath*:org/nix/zpbs/mapper/*.xml